name: calendary
version: '1.0.5'
summary: A calendar app build using ElectronJS.
description: |
   A minimal calendar by Hajime. 
grade: devel
confinement: devmode
parts:
  gnu-hello:
    source: https://github.com/Hajime4th/Calendar.git
    plugin: autotools
